git mv --force "Fluent1.png" "Pics\Fluent 1.png"
git mv --force "Fluent2.png" "Pics\Fluent 2.png"
git mv --force "Fluent3.png" "Pics\Fluent 3.png"
git mv --force "HPC Website 1.png" "Pics\HPC Website 1.png"
git mv --force "HPC Website 2.png" "Pics\HPC Website 2.png"
git mv --force "linkedin qr-code.png" "Pics\Linkedin QR-Code.png"
git mv --force "Sharif ID.png" "Pics\Sharif ID.png"
git mv --force "Sharif Logo Farsi.png" "Pics\Sharif Logo Farsi.png"
git mv --force "WinSCP0.png" "Pics\WinSCP 01.png"
git mv --force "WinSCP1.png" "Pics\WinSCP 02.png"
git mv --force "WinSCP2.png" "Pics\WinSCP 03.png"
git mv --force "WinSCP3.png" "Pics\WinSCP 04.png"
git mv --force "WinSCP4.png" "Pics\WinSCP 05.png"
git mv --force "WinSCP5.png" "Pics\WinSCP 06.png"
git mv --force "WinSCP8.png" "Pics\WinSCP 07.png"
git mv --force "WinSCP9.png" "Pics\WinSCP 08.png"
git mv --force "WinSCP10.png" "Pics\WinSCP 09.png"
git mv --force "WinSCP13.png" "Pics\WinSCP 10.png"